name: patch-boot

on:
  push:
  workflow_dispatch:

jobs:
  patch:
    strategy:
      matrix:
        ota_url:
          - https://cdnorg.d.miui.com/OS1.0.5.0.TKXMIXM/nabu_global_images_OS1.0.5.0.TKXMIXM_20240826.0000.00_13.0_global_e32cdbaf9f.tgz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download ota
        run: |
          wget ${{ matrix.ota_url }} -O ota.tgz
          tar zxvf ota.tgz
          find .
